#!/usr/bin/python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys

fileDict = {}

baseDir = os.getcwd()
extraDirs = 0

for item in sys.argv[1:]:
    if item.startswith('-p'):
        extraDirs = True
    else:
        baseDir = item

baseDir = os.path.realpath(baseDir)

newFile = None
for line in sys.stdin.readlines():
    if line.startswith('---'):
        oldFile = line.split()[1]
    elif line.startswith('+++'):
        newFile = line.split()[1]
        if extraDirs:
            while not os.path.exists(os.path.join(baseDir, newFile)):
                newFile = os.path.sep.join(newFile.split(os.path.sep)[1:])
        newFile = os.path.join(baseDir, newFile)

        fileDict.setdefault(newFile, [])
    elif line.startswith('@@'):
        curLine = int(line.split()[2].split(',')[0][1:])
    elif line.startswith('+'):
        fileDict[newFile].append(curLine)
        curLine += 1
    elif line.startswith('-'):
        continue
    elif newFile:
        curLine += 1

for file in sorted(fileDict):
    print file
    print ' '.join(str(x) for x in sorted(fileDict[file]))
